apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: udagram-api-user
          image: lajcik007/udagram-api-user
          ports:
            - containerPort: 80
        - name: udagram-api-feed
          image: lajcik007/udagram-api-feed
          ports:
            - containerPort: 81