apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-app
  labels:
    service: udagram-api-feed-app
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: udagram-api-feed-app